nodes:

  alpha:
    # alpha node does not expose endpoints

  beta:
    - name: "beta.svc"

      endpoints:
      - address: 10.123.0.21
        port: 3000
        annotations:
          # play with these values and check the jaeger dashboard
          fault.inject: ""
          fault.delay.duration: "50"
          fault.delay.percent: "15"
          fault.abort.code: "583"
          fault.abort.percent: "5"
          endpoint.weight: 95

  beta.2:
    - name: "beta.svc"
      annotations:

      endpoints:
      - address: 10.123.0.22
        port: 3000
        annotations:
          endpoint.weight: 5

  gamma:
    - name: "gamma.svc"
      endpoints:
      - address: 10.123.0.23
        port: 3000

  delta:
    - name: "delta.svc"
      endpoints:
      - address: 10.123.0.24
        port: 3000
        annotations:
          healthcheck.path: "/XXXXXXXXXXXXXX"
          healthcheck.cache: "60000"

  epsilon:
    - name: "epsilon.svc"
      endpoints:
      - address: 10.123.0.25
        port: 3000

  zeta:
    - name: "zeta.svc"
      endpoints:
      - address: 10.123.0.26
        port: 3000
        annotations:
          fault.inject: ""
          fault.abort.code: "583"
          fault.abort.percent: "15"

  eta:
    - name: "eta.svc"
      endpoints:
      - address: 10.123.0.27
        port: 3000
        annotations:
          fault.inject: ""
          fault.delay.duration: "50"
          fault.delay.percent: "30"
