nodes:

  alpha:
    # alpha node does not expose endpoints

  beta:
    - name: "beta.svc"
      annotations:
        # play with these values and check the jaeger dashboard
        fault.inject: "1"
        fault.delay.duration: "150"
        fault.delay.percent: "10"
        fault.abort.code: "501"
        fault.abort.percent: "5"
      endpoints:
      - address: 10.123.0.21
        port: 3000

  beta.2:
    - name: "beta.svc"
      annotations:
        fault.inject: "1"
        fault.delay.duration: "30"
        fault.delay.percent: "5"
        fault.abort.code: "501"
        fault.abort.percent: "5"
      endpoints:
      - address: 10.123.0.22
        port: 3000

  gamma:
    - name: "gamma.svc"
      annotations:
        enable-retry: ""
        num-retries: "4"
      endpoints:
      - address: 10.123.0.23
        port: 3000

  delta:
    - name: "delta.svc"
      endpoints:
      - address: 10.123.0.24
        port: 3000

  epsilon:
    - name: "epsilon.svc"
      endpoints:
      - address: 10.123.0.25
        port: 3000

  zeta:
    - name: "zeta.svc"
      endpoints:
      - address: 10.123.0.26
        port: 3000

  eta:
    - name: "eta.svc"
      endpoints:
      - address: 10.123.0.27
        port: 3000
