version: '2'

services:

  controlplane:
    image: moolen/bent:latest
    command: "-provider file -config /config.yaml"
    volumes:
      - "./config.yaml:/config.yaml"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.2

  jaeger:
    image: jaegertracing/all-in-one:1.10
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "16686:16686"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.3

  # authz "pod"
  authz:
    image: moolen/envoy-authz:latest
    environment:
      ENVOY_NODE_ID: "authz"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_SERVICE_NAME: "authz"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      AUTH_USER: "jimmy"
      AUTH_PASS: "1234"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.9

  # ingress "pod"
  ingress:
    image: moolen/bent-envoy:latest
    environment:
      ENVOY_NODE_ID: "ingress"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_AUTHZ_ADDRESS: "authz"
      ENVOY_AUTHZ_PORT: "8080"
      ENVOY_JAEGER_SERVICE_NAME: "ingress"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
    ports:
      - "9999:9999"
      - "4100:4100"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.10

  # alpha "pod"
  alpha:
    image: moolen/envoy-egress:latest
    environment:
      ENVOY_NODE_ID: "alpha"
      ENVOY_JAEGER_SERVICE_NAME: "alpha"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      TARGET: http://beta.svc
      TIMER: 1
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.20

  # beta "pod"
  beta:
    image: moolen/envoy-fwd:latest
    environment:
      ENVOY_NODE_ID: "beta"
      ENVOY_JAEGER_SERVICE_NAME: "beta"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      TARGET: "http://gamma.svc/from/beta,http://zeta.svc/from/beta"
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.21

  # beta "pod"
  beta.2:
    image: moolen/envoy-fwd:latest
    environment:
      ENVOY_NODE_ID: "beta.2"
      ENVOY_JAEGER_SERVICE_NAME: "beta.2"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      TARGET: "http://gamma.svc/from/beta,http://zeta.svc/from/beta"
      SERVICE_NAME: "beta2-fwd"
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.22

  # gamma "pod"
  gamma:
    image: moolen/envoy-fwd:latest
    environment:
      ENVOY_NODE_ID: "gamma"
      ENVOY_JAEGER_SERVICE_NAME: "gamma"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      TARGET: "http://delta.svc/from/gamma,http://eta.svc/from/gamma,http://epsilon.svc/from/gamma"
      SERVICE_NAME: "gamma-fwd"
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.23

  # delta "pod"
  delta:
    image: moolen/envoy-echo:latest
    environment:
      ENVOY_NODE_ID: "delta"
      ENVOY_JAEGER_SERVICE_NAME: "delta"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      PORT: "3000"
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.24

  # epsilon "pod"
  epsilon:
    image: moolen/envoy-echo:latest
    environment:
      ENVOY_NODE_ID: "epsilon"
      ENVOY_JAEGER_SERVICE_NAME: "epsilon"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      PORT: "3000"
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.25

  # zeta "pod"
  zeta:
    image: moolen/envoy-echo:latest
    environment:
      ENVOY_NODE_ID: "zeta"
      ENVOY_JAEGER_SERVICE_NAME: "zeta"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      PORT: "3000"
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.26

  # eta "pod"
  eta:
    image: moolen/envoy-echo:latest
    environment:
      ENVOY_NODE_ID: "eta"
      ENVOY_JAEGER_SERVICE_NAME: "eta"
      ENVOY_XDS_HOST: "controlplane"
      ENVOY_JAEGER_AGENT_HOST: "jaeger"
      ENVOY_JAEGER_AGENT_PORT: "6831"
      PORT: "3000"
      http_proxy: "http://127.0.0.1:4000"
    networks:
      vpcbr:
        ipv4_address: 10.123.0.27

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.123.0.0/24
         gateway: 10.123.0.1
